HMake doc structure consistent and up-to-date   obgoblin
kivy/kivy-sdk-packager pull request #96
Opened 2023-12-05 13:14 UTC by Julian-O

This is part of an effort to make the Kivy sibling projects' documentation structure consistent and up-to-date.

Unrelated items:
* Readme was vestigial. Wrote description from scratch.

CHECKLIST

* CONTRIBUTING.md
   [x] If repo takes user contributions, is present
   [x] In root dir (not .github dir)
   [x] Explains relationship to Kivy, if unclear.
   [x] Refers to kivy/kivy Contribution Guidelines.
   
* LICENSE
   [x] If repo takes user contributions, is present.
   [x] Acknowledges the range of years to 2023.
   [x] Acknowledges Kivy Team and other contributors
   [x] Mentions it is an MIT License.
   
* CODE_OF_CONDUCT.md
   [x] If repo takes user contributions or hosts discussions, is present.
   [x] Refers to kivy/kivy CODE_OF_CONDUCT.md
   
* CONTACT.md
   [x] Refers to kivy/kivy CONTACT.md

* FAQ.md
   [NA] If repo is big enough for RST documentation, is present.
   
* README:
   [x] Is a Markdown file.
   [x] Describes the project.
   [x] Describes its place in the Kivy sibling projects.
   [NA] If Documentation exists, mention it.
   [x] If CONTRIBUTING exists, mentions it.
   [x] If LICENSE exists, mentions it.
   [x] If CODE_OF_CONDUCT exists, mentions it.
   [x] Mentions kivy/kivy CONTACT.md
   [NA] Uses Python syntax colouring for embedded Python code.
   [x] Uses badges to display current status, including:
        [x] Backers
		[x] Sponsors
		[x] GitHub contributors
		[x] Contributor Covenant
		[NA] PyPI Version
		[NA] PyPI Python Version
		[x] Build/Test status

   [x] Displays all contributors to the repo.		
   [x] Displays backers
   [x] Displays top sponsors.

* RST documentation, if present
   [NA] Describes the project.
   [NA] Describes its place in the Kivy sibling projects.
   [NA] Mentions (Kivy/Kivy) Contact Us link.
   [NA] Mentions LICENSE.
   [NA] Mentions CONTRIBUTING
   [NA] Mentions FAQ
   [NA] conf.py mentioned Kivy Team and other contributors
		- copyright, latex_documents, man_pages, texinfo documents
   
   
* WORKFLOWS
   [NA] NO_RESPONSE.yml is present if the repo has awaiting_reply tag.
   [NA] NO_RESPONSE uses latest script versions.
   [NA] SUPPORT.yml is present if the repo has a `support` tag.
   [NA] SUPPORT.yml refers to repo's CONTACT.md

* setup.py/cfg, if present and on PyPI
   Note: Template used for Kivy SDK for Windows 
   [too hard] Supplies description to PyPI
   [too hard] Supplies Python versions to PyPI
   [x] Supplies Documentation, if any, to PyPI

2023-12-05 17:18 UTC, misl6 commented on README.md
> +to build and distribute them.
Not properly, `kivy-sdk-packager` has multiple purposes (and I wonder if would be better to split it into multiple repos in the future).

- Windows:
    - We have scripts to build dependencies to run Kivy (Such as `sdl2`, `glew`and `angle`)
 - Linux (debian):
    - `kivy-sdk-packager` hosts the files needed during the execution of the build on Ubuntu PPA
 - macOS:
     - `kivy-sdk-packager` hosts the scripts needed to package a `.dmg` or `.app` (can be the `Kivy.app` we distribute when a new Kivy release is produced, or can be used by our users to package their Kivy-based app for macOS)

2023-12-05 17:30 UTC, misl6 requested changes
Hi @Julian-O .

I left some comments, and we need to fix the README before the merge.
If you need some more explanations, feel free to ping me on Discord.

**Important note:**
Except for macOS scripts, we do not expect "standard users" to use any other feature of `kivy-sdk-packager` directly.

2023-12-05 17:30 UTC, misl6 commented on README.md
> +[![GitHub contributors](https://img.shields.io/github/contributors-anon/kivy/kivy-sdk-packager)](https://github.com/kivy/kivy-sdk-manager/graphs/contributors)
```suggestion
[![GitHub contributors](https://img.shields.io/github/contributors-anon/kivy/kivy-sdk-packager)](https://github.com/kivy/kivy-sdk-packager/graphs/contributors)
```

2023-12-05 17:30 UTC, misl6 commented on README.md
> +specifications (recipes) provided here.
See above (the explanation about `kivy-sdk-packager`)

2023-12-05 17:30 UTC, misl6 commented on README.md
> +Kivy SDKs for macOS are built as Disk Image (DMG) files.
See above (the explanation about `kivy-sdk-packager`)

2023-12-05 17:30 UTC, misl6 commented on README.md
> +Kivy SDK for Windows are built as wheels that can be installed via
Is not an SDK (see explanation above)

2023-12-05 17:30 UTC, misl6 commented on README.md
> +| [SDL2](https://www.libsdl.org/)                                         | [kivy-deps.sdl2](https://pypi.org/project/kivy-deps.sdl2/)           |
This is not true 😅

See:
- https://kivy.org/doc/stable/api-kivy.graphics.cgl.html
- https://kivy.org/doc/stable/gettingstarted/installation.html#installing-kivy-s-dependencies

2023-12-08 10:01 UTC, misl6 requested changes
We're almost there 🏁

I've left some minor comments regarding typos, and outdated content.

2023-12-08 14:55 UTC, Julian-O commented
@misl6: Thanks! Done.

Great news about setting the deploy target. Removed warning from the macOS README too.

2023-12-08 15:00 UTC, merged